import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}, bg-green-500`}>
        <div className="bg-white p-5 flex gap-10">
          <Link href="/" className="font-bold hover:text-zinc-300">HOME</Link>
          <Link href="/list" className="font-bold hover:text-zinc-300">LIST</Link>
          <Link href="/cart" className="font-bold hover:text-zinc-300">CART</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
